### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jordansexton** [CRAlpha/react-native-wkwebview#1]
Hey! Good to see someone is taking this on since I don't use it now. I don't have any issue with having the project be a fork or not. However, [per this comment](https://github.com/CRAlpha/react-native-wkwebview/commit/a96cf73b2c962efd29efb131cd0bb6ec487b301a#commitcomment-17705340) the original MIT license and copyright notice must be preserved. Specifically:

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

You're not obligated in any way to maintain a fork, or even link to the original if you don't want to, but the terms of the license require that the original license be distributed with the software. Just add your own copyright line to it as well, [like this](https://github.com/XaminProject/handlebars.php/issues/57#issuecomment-37617369). It seems like you're more actively developing this than I am, but I'll happily pull request any updates I end up making in my own code.

**Comment by insraq** [comment]
Let's me fix that. Thanks for pointing this out

**Comment by insraq** [comment]
@jordansexton Just curious, what should I put into the License if some of the code are derived from React Native Core itself?

**Comment by jordansexton** [comment]
Hah, yeah, I will update the original as well! It's definitely derivative :)

**Comment by jordansexton** [comment]
Updated: https://github.com/jordansexton/react-native-wkwebview/commit/026d12e7beed9d739129a435f430e5ff0096dbdc

Facebook uses the BSD license for this, so I think it makes sense to separate them here.
