### ISSUE TITLE
Missing HTTP headers when go to another link

### ISSUE THREAD

**Issue by adziubin** [CRAlpha/react-native-wkwebview#100]
Missing HTTP headers when go to another link

`state = {
        url: "https://www.site-example.com",
   };
    renderWebView() {

       if (Platform.OS === 'ios') {
           let customHeaders = {
               "X-OS": "iOS"
           };

           return (
               <WKWebView
                   onProgr ess={(progress) => console.log(progress)}
                   onLoadSt art={(navState) => this.setState({url: navState.nativeEvent.url})}
                   source={{uri: this.state.url, headers: customHeaders}}
                   st yle={{marginTop: 20}}
               />
           );
       }`

**Comment by adziubin** [comment]
When i go in webview to another page, headers is missing

**Comment by insraq** [comment]
`headers` are only sent on initial load. Subsequent requests follow the default behavior of WebView - the component doesn't hijack the link.
