### ISSUE TITLE
Can you use this on Android as well? 

### ISSUE THREAD

**Issue by AlmogRnD** [CRAlpha/react-native-wkwebview#104]
Does this webview work on Android as well?

**Comment by squgeim** [comment]
No. This is a wrapper for [`WKWebView`](https://developer.apple.com/documentation/webkit/wkwebview) on ios.

If you look at [`WKWebView.android.js`](https://github.com/CRAlpha/react-native-wkwebview/blob/master/WKWebView.android.js), you will see that it is empty.

**Comment by rgoldiez** [comment]
I'm curious why this component doesn't return the standard `WebView` from WKWebView.android.js so that at the very least the user doesn't have to do that on app that are cross platform?

**Comment by rgoldiez** [comment]
@insraq - I created a PR here to resolve this:  https://github.com/CRAlpha/react-native-wkwebview/pull/142
