### ISSUE TITLE
Build failed due to iOS version check

### ISSUE THREAD

**Issue by mmorier** [CRAlpha/react-native-wkwebview#111]
Hello,

React Native can't run my app since I add `react-native-wkwebview-reborn` as dependency. Error is the following:
```sh
/node_modules/react-native-wkwebview-reborn/ios/RCTWKWebView/RCTWKWebViewManager.m:49:1: error: expected identifier or '('
if (@available(iOS 9, *))
^
1 error generated.
```

No problem if I remove the if statement. I use RN 0.53 and Xcode 9.2.

**Comment by kinkoi** [comment]
Hi, I saw the same error.

**Comment by insraq** [comment]
It should work on XCode >=9, are you using an older version of XCode?

**Comment by TheAlmightyBob** [comment]
@insraq I see this error with XCode 9.2 (and @mmorier also said he was using 9.2)

**Comment by conghai** [comment]
+1
I have been same error!

My XCode: Version 9.2 (9C40b)

**Comment by insraq** [comment]
New version published on npm: 1.13.0. Hope this should fix the error.

**Comment by alexisbronchart** [comment]
I've been specifically asked too add this version check before my PR was merged. I do agree that iOS 8 is probably no longer used a lot but maybe we should also update the README which still mentions "Deployment Target >= iOS 8.0 is required".

**Comment by insraq** [comment]
@alexisbronchart The patch I made still has the version check, but in a different way.
