### ISSUE TITLE
Crash On Reload on iOS 9.3 Simulator

### ISSUE THREAD

**Issue by rangav** [CRAlpha/react-native-wkwebview#115]
Hi 

Component is crashing when i reload the App on iOS 9.3 Simulator

Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

```
<WKWebView source={{uri: 'https://github.com/facebook/react-native'}}
        style={{ marginTop: 20 }}
      />);
```

Any suggestion to fix this?

**Comment by rangav** [comment]
Hi 

Its still crashing the app, when App Reload(not browser reload) which is CMD + R. 

Can you please reopen the issue.

**Comment by insraq** [comment]
What's your `react-native-wkwebview` version?

**Comment by rangav** [comment]
Sorry its working now with latest version 1.16.0. Thanks for fixing it.
