### ISSUE TITLE
Error -1100: NSURLErrorDomain

### ISSUE THREAD

**Issue by AmitM30** [CRAlpha/react-native-wkwebview#118]
Hi,

I must be missing something too obvious, but when trying to load `index.html` in wkwebview, I am getting:
![image](https://user-images.githubusercontent.com/10666012/36962142-5e05bfc2-2074-11e8-9658-2b9c6582678c.png)

Project Structure (src/web/index.html):
![image](https://user-images.githubusercontent.com/10666012/36962214-a29acd44-2074-11e8-9592-800b34d63257.png)

`<WKWebView source={{ file: RNFS.MainBundlePath + '/src/web/index.html', allowingReadAccessToURL: RNFS.MainBundlePath }} />`

**Comment by insraq** [comment]
I think by default, src folder is not bundled in the package? You need to either manually copy the file or change the bundler.

**Comment by AmitM30** [comment]
You are right. Actually when running in debug mode, RN seems to boot up a local server on port 8081, and the url with http://localhost:8081 seems to do the job, but same did not work in release mode.

I need to find a way to copy the src folder into the app.

Thanks !
