### ISSUE TITLE
webview side don't receive the message

### ISSUE THREAD

**Issue by bestlbw** [CRAlpha/react-native-wkwebview#128]
in react-native side ,i use `postMessage` like webview,but i can't receive the message in webview side like this  `window.document.addEventListener('message', function (e) {  })`
also,  i try to learn from your example ,doesn't it , it call err  
RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSURL) 
could you  help me?

**Comment by Tinayu0915** [comment]
I encountered the same problem as you did. I  can't receive the message in webview side like this `window.document.addEventListener('message', function (e) { })`.How did you fix this question? 
@bestlbw
