### ISSUE TITLE
_processPool causes EXC_BREAKPOINT

### ISSUE THREAD

**Issue by craftzdog** [CRAlpha/react-native-wkwebview#130]
3e0162987ac7bf4175f94625edc44565d107fe2d causes my app crashing due to following error:

```
com.facebook.react.JavaScript (9): EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
```

If I reverted that change, it works again.

RN@0.53.0

**Comment by ouabing** [comment]
Same problem after upgrading to 1.17.0

**Comment by insraq** [comment]
I tried to reproduce it in the example app in the repository, but failed. Can you share more about the error message and how's component being used?

**Comment by insraq** [comment]
Hmm. I think I know the issue here. I've made a commit making sure the process pool is a global singleton. This should solve the issue. https://github.com/CRAlpha/react-native-wkwebview/commit/cc091137ba2971f01cb6b3f97a3b77845baf84c8

It's on npm@1.18.0, let me know if it works.

**Comment by craftzdog** [comment]
It worked! Thank you for the quick fix.
