### ISSUE TITLE
evaluateJavaScript does not work for DOM js any more since 1.14

### ISSUE THREAD

**Issue by abinli** [CRAlpha/react-native-wkwebview#138]
Hi,

I was trying to upgrade from an older version (1.10) to the latest 1.18, and found that evaluateJavaScript() broke since version 1.14 for any DOM related js (such as getElementById)

Any suggestions? (Do I need to do any special setup from version 1.14 on)?

Thanks!

**Comment by abinli** [comment]
@insraq here is some sample js:
js = 'window.location.href = "https://www.google.com/"; var content = document.body.outerHTML;'
wkwebview.evaluateJavaScript(js);

Basically, since 1.14, any js code accessing DOM stopped working.

Thanks,
Abinli

**Comment by insraq** [comment]
I tried with `this.webview.evaluateJavaScript('window.postMessage({content: document.body.outerHTML})')` and it works fine for me. I am not sure if change `window.location.href`, the code after that will work.

**Comment by abinli** [comment]
@insraq Thanks for verifying! Good to know other DOM operations work except window.location.ref. Yes, I think window.location.href broke since 1.14, since it's the 1st statement in my script.

Any suggestions to fix it?

Thanks,
Abinli

**Comment by insraq** [comment]
I read through the commits for 1.14 but cannot find any specific change regarding this. Are you sure it ever worked?

**Comment by abinli** [comment]
@insraq yeah, "window.location.href" is the first statement in my js, and worked in my project for more than 1 year. I just verified again for each recent version of react-native-wkwebview.

-Abinli

**Comment by shirakaba** [comment]
In my macOS fork of `react-native-wkwebview`, which is up-to-date with the current master (1.20.0), it works perfectly directly:

```js
this.webView.evaluateJavaScript(`alert(window.location.href);`);
```

... And also when posting as a message to be handled by my message handler:

```js
this.webView.evaluateJavaScript(`window.webkit.messageHandlers.reactNative.postMessage({ controller: "test", message: window.location.href })`);
```

```ts
<WKWebView
    // ... Other props
    onMessage={(ev) => {
        const data = ev.nativeEvent.data;

        switch(data.controller){
            case "test":
                console.log(`Received posted test message. body is: ${data.message}`);
                break;
            default:
                // Do nothing for this particular test.
        }
    }}
/>
```

I don't, however, alter `window.location.href` directly; I alter it by calling `setState()` upon the 'source' prop, e.g.: `source={{ uri: this.state.url }}`. Maybe this is where you're experiencing friction..? Or is it a race condition? Could you hook up a button to `evaluateJavaScript()` to see whether `window.location.href` eventually is resolved correctly? If so, then you just need to determine the better prop out of `injectJavaScript` or `injectedJavaScript` to do your `window.location.href` business at the right moment in the page's lifecycle.

<img width="839" alt="screen shot 2018-05-31 at 19 31 54" src="https://user-images.githubusercontent.com/14055146/40800808-4b99e294-6509-11e8-8859-b33ae24b9a53.png">

**Comment by abinli** [comment]
@shirakaba great, let me try it out :)

--Abinli

**Comment by abinli** [comment]
@insraq @shirakaba The issue disappeared in 1.20, closing the bug.

Thanks for the help!

--abinli
