### ISSUE TITLE
react-native reload crashes on _processPool

### ISSUE THREAD

**Issue by scisci** [CRAlpha/react-native-wkwebview#143]
Hi, whenever I reload my react-native app it crashes around something in the _processPool. I noticed this was removed in this commit: https://github.com/CRAlpha/react-native-wkwebview/commit/cc091137ba2971f01cb6b3f97a3b77845baf84c8#diff-6f7ebd00ed33033847ab152769db0f4d, which should fix the issue, but a release hasn't happened since then, so I'm not able to update.

**Comment by insraq** [comment]
This fix was on NPM since 1.18.0

**Comment by scisci** [comment]
sorry, didn't realize it was published, for some reason was only seeing 1.17.0, must be blind, thanks.
