### ISSUE TITLE
[Question] Is the non-default scrolling inertia done on purpose?

### ISSUE THREAD

**Issue by zefre** [CRAlpha/react-native-wkwebview#145]
On a normal, native WKWebView, the deceleration rate of the scroll seems to be much lower than it is when using this WebView. Is this intentional? If not, I can make a PR

**Comment by insraq** [comment]
I don't think it's intentional. But I do not recall there's any specific code regarding scroll deceleration. Feel free to make a PR though :-)

**Comment by zefre** [comment]
Will do, Thanks!
