### ISSUE TITLE
Implement RefreshControl for wkwebview

### ISSUE THREAD

**Issue by ankur-sardar** [CRAlpha/react-native-wkwebview#150]
is there any way to implement [RefreshControl](https://facebook.github.io/react-native/docs/refreshcontrol.html) feature for webview? Are you planning to implement this?

**Comment by shirakaba** [comment]
This is the React Native implementation of iOS's `UIRefreshControl`, right? WebViews don't typically come with that – they come with a `UIProgressView` instead, which there is a RN implementation for: [ProgressViewIOS](https://facebook.github.io/react-native/docs/progressviewios.html). I've only ever seen `UIRefreshControl` on a searchable list of items (e.g. in Apple Mail). Can you provide an example of the context this would be used in?

**Comment by ankur-sardar** [comment]
Example - If we want to add the feature pull down the webview to refresh the webview

**Comment by shirakaba** [comment]
So this webView would have vertical scrolling disabled?

Why don't you just embed the webView, with scrolling disabled, into another component that already supports the RefreshControl, like a ListView (not exactly sure what it's called) with no padding – such that the webView is flush with the edges of the ListView? I think that's the usual way to do it, in any case.

**Comment by ankur-sardar** [comment]
I tried one workaround, 
I wrapped the <wkwebview> with <ScrollView> like this

```
<ScrollView 
          refreshControl={
            <RefreshControl
              refreshing={false}
              onRefresh={this.props.refresh}
            />
          }
          contentContainerStyle={{flex: 1}}
          scrollsToTop={false}
          style={{backgroundColor: 'white'}}
          canCancelContentTouches={false}
        >

<WkWebView...../>

</ScrollView>

```

Is it a good idea to use it like this?

**Comment by shirakaba** [comment]
I think that is realistically the easiest (and possibly only) way to achieve what you want in React Native without changing the `react-native-wkwebview` framework itself. Note that you may need to determine a much more sophisticated/complex solution if you need vertical scrolling in the `WKWebView` *as well as* the `RefreshControl` functionality from the parent `ScrollView`. But if what you've written so far seems to work, then well done!

The ideal approach would be to change the native code of `react-native-wkwebview` to support your feature, but it might be hard. Here is some guidance on possible ways to implement it:

- https://stackoverflow.com/questions/38156954/pull-to-refresh-not-working-in-ios-webview
- https://stackoverflow.com/questions/33996264/pull-to-refresh-on-uiwebview (note: refers to `UIWebView`, but implementation may be applicable)
- https://stackoverflow.com/questions/13379815/use-uirefreshcontrol-for-uiwebview (has some answers using `WKWebView`)

I think that this feature is ultimately out of the scope for this project, however (this project just provides the `WKWebView` implementation, nothing more); if you want to pursue a native solution to this, I would suggest forking this project and making the changes you need based on those StackOverflow links above.
