### ISSUE TITLE
Regression in 1.20.0: onMessage (postMessage) not working

### ISSUE THREAD

**Issue by ibc** [CRAlpha/react-native-wkwebview#159]
Calling `window.postMessage()` within the app running in the `<WKWebView>` no longer works in react-native-wkwebview 1.20.0. It **does work** in 1.19.0 (tested).

* This is the [diff](https://github.com/CRAlpha/react-native-wkwebview/compare/af95388...7a0d6af) between 1.19.0 and 1.20.0:
* Suspicious [commit](https://github.com/CRAlpha/react-native-wkwebview/commit/29588d4144940864126c689c4c400eb215f72adf).

To be more clear: `setupPostMessageScript()` does **NEVER** setup the `postMessage` stuff because it checks `_messagingEnabled` which is **NEVER** set to `true`:

https://github.com/CRAlpha/react-native-wkwebview/blob/master/ios/RCTWKWebView/RCTWKWebView.m#L134

```objective-c
- (void)setupPostMessageScript {
  if (_messagingEnabled) {
    NSString *source=@"window.originalPostMessage = window.postMessage; window.postMessage = function (data) { window.webkit.messageHandlers.reactNative.postMessage(data); }";
    WKUserScript *script = [[WKUserScript alloc] initWithSource:source
                           injectionTime:WKUserScriptInjectionTimeAtDocumentEnd
                                               forMainFrameOnly:_injectedJavaScriptForMainFrameOnly];
    [_webView.configuration.userContentController addUserScript:script];
  }
}
```

Note that `_messagingEnabled` is **NEVER** defined, declared or set in the whole code.

/cc @ivmos @jmillan

**Comment by ibc** [comment]
If a new prop `messagingEnabled` is required for `postMessage()` to work, it's ok, but it's not documented.

**Comment by ibc** [comment]
By removing the `if (_messagingEnabled) {` line, it works. Of course, we are passing the `onMessage` function prop.

**Comment by priteshpoddar** [comment]
Same for me when I downgrade to 1.19.0 the onMessage is firing.

**Comment by insraq** [comment]
PR #165 should have fixed it. It's on npm 1.21.0

**Comment by priteshpoddar** [comment]
Do we need to pass messagingEnabled props?

**Comment by priteshpoddar** [comment]
It is working.
Not required.
Thanks
