### ISSUE TITLE
injectJavaScript in not function 

### ISSUE THREAD

**Issue by manoj2166** [CRAlpha/react-native-wkwebview#178]
Hi,
I am using 
"react-native-wkwebview-reborn": "^1.21.0" and try to inject custom script after loaded with injectJavaScript but showing me injectJavaScript in not a function.

Please let me know how can I do it, 
It is working fine when I am using default react-native webview.

**Comment by shirakaba** [comment]
`injectJavaScript` is a prop, and only a prop.

`evaluateJavaScript` is the function, just as it is for the real WKWebView in iOS/macOS.

Does this solve your issue?

**Comment by manoj2166** [comment]
Hi @shirakaba,

Thanks, it is working but once call reload function it stops working.

**Comment by shirakaba** [comment]
Can you post a minimal code example to to reproduce this?

**Comment by manoj2166** [comment]
by use of evaluateJavaScript function is working fine.
I am closing this issue.
thanks
