### ISSUE TITLE
add support for postMessage

### ISSUE THREAD

**Issue by tomprogers** [CRAlpha/react-native-wkwebview#18]
The native WebView supports postMessage for communication between the embedded web page and the native app.

WKWebView has vastly better performance, but doesn't appear to support postMessage. For us, that's a deal-breaker. I'm investigating workarounds, but am not optimistic (I'm neither an Obj-C nor Java dev).

Please add support for postMessage.

**Comment by insraq** [comment]
Fixed by 6caf66be16b0caddae0bd1d53b8503a6853fd027
