### ISSUE TITLE
is it works on 4.4.2 android version | 16 api level and more ?

### ISSUE THREAD

**Issue by BlackSword101** [CRAlpha/react-native-wkwebview#180]
hi great one, but just need to ask if it works on 4.4.2 android version | 16 api level and more

**Comment by insraq** [comment]
WkWebView is iOS-only, as its name suggests.

**Comment by insraq** [comment]
WkWebView is iOS only. Android will simply use React Native's WebView.

**Comment by BlackSword101** [comment]
ok thanks for this , but i'm web dev and i don't know if WebView works on 16 api level or not please can help me and thanks
