### ISSUE TITLE
injectedJavaScript doesn't work

### ISSUE THREAD

**Issue by tomprogers** [CRAlpha/react-native-wkwebview#19]
I ran a test to compare react-native's built-in WebView with react-native-wkwebview's WKWebView. The WebView executes the injected script, and the WKWebView does not appear to.

Sample code:

```
'use strict';

import React, {
	Component
} from 'react';
import {
	Text,
	WebView,
	View
} from 'react-native';
import Styles from './styles';
import WKWebView from 'react-native-wkwebview';


export default class Scene extends Component {
	
	render() {
		let js = `alert('test');`;
		
		return (
			<View style={Styles.SCENE}>
				
				<WKWebView style={Styles.BROWSER}
					source={{uri: `http://localhost:3000`}}
					messagingEnabled={true}
					onMessage={this.onMessage}
					injectedJavaScript={js}
				/>
				
			</View>
		);
	}
	
};
```

When I render a `WebView`, the javascript alert appears once the web page has loaded. When I render a `WKWebView`, the javascript alert never appears. Unless WKWebView has some kind of setting that suppresses `alert`, this seems prove that WKWebView's support for the `injectedJavaScript` prop is broken.

**Comment by insraq** [comment]
Alert is not supported by iOS's WKWebView by default. See http://stackoverflow.com/questions/26898941/ios-wkwebview-not-showing-javascript-alert-dialog

Try chagne your code to `injectedJavaScript={'document.write("<h1>Test</h1>")'}` and you will see the result.
