### ISSUE TITLE
how to Sending parameters to Local File 

### ISSUE THREAD

**Issue by testxin** [CRAlpha/react-native-wkwebview#193]
<WKWebView 
    source={{
       file: RNFS.MainBundlePath + '/www/a.html?a=1',
        allowingReadAccessToURL: RNFS.MainBundlePath   }}
/>
when i write like this will throws NSURLErrorDomain

**Comment by shirakaba** [comment]
For clarification: this is an OS-level problem, not a WKWebView problem.

If you want URL params, you'll have to find some way to serve your file over HTTP.
