### ISSUE TITLE
Allowing mixed content  in WkWebView

### ISSUE THREAD

**Issue by wkwyatt** [CRAlpha/react-native-wkwebview#206]
I have an app that loads an insecure JS resource over `http` and because of that the webview will not load.  Is there a way to allow the mixed content to load? 

I have already tried updating the ATS

**Comment by shirakaba** [comment]
Nope. That’s just the WebKit team implementing the relevant web security specs correctly.

You can load JS over HTTP if your site is on a HTTP domain.
