### ISSUE TITLE
Alternative #2 run fail

### ISSUE THREAD

**Issue by 277850318** [CRAlpha/react-native-wkwebview#21]
![image](https://cloud.githubusercontent.com/assets/8946022/20859308/f56c4ac6-b995-11e6-95b0-43b0bd143d49.png)
![image](https://cloud.githubusercontent.com/assets/8946022/20859309/0290c52e-b996-11e6-9202-b85cdbc80646.png)
![image](https://cloud.githubusercontent.com/assets/8946022/20859310/0811c430-b996-11e6-96a3-e025a875e9f8.png)

**Comment by insraq** [comment]
It's already noted in the README. The rpm link way does not work well with iOS 8.
