### ISSUE TITLE
UIManager['CRAWKWebView'] is no longer supported

### ISSUE THREAD

**Issue by indapublic** [CRAlpha/react-native-wkwebview#222]
![screenshot 2019-02-22 at 10 18 22](https://user-images.githubusercontent.com/856260/53210912-33449f00-368b-11e9-9618-2c7781219fe5.png)

I receive warning while running `goBack` method.

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 128.72 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.5 => 0.58.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

```
"react-native-wkwebview-reborn": "^2.0.0",
```

**Comment by shirakaba** [comment]
This is an issue with the (newer) version of React Native you're using, not an issue with this repo. As the warning suggests, use `UIManager.getViewManagerConfig('CRAWKWebView')` instead.

**Comment by indapublic** [comment]
@shirakaba It's related to this repo code, not mine. 
https://github.com/CRAlpha/react-native-wkwebview/blob/master/WKWebView.ios.js#L399

**Comment by insraq** [comment]
I haven't followed React Native for a while. Looking at the warning, it seems the code is deprecated. Feel free to submit a PR and I'll be happy to merge it. Although I am not sure whether this change will be backward compatible.

**Comment by shirakaba** [comment]
@indapublic Sorry for the misunderstanding; I see what you mean. A PR would be appreciated.

> Although I am not sure whether this change will be backward compatible.

Yes – at the very least, this should involve a check of whether the method `getViewManagerConfig` really exists on `UIManager`. If it exists, use `UIManager.getViewManagerConfig('CRAWKWebView')`; otherwise, fall back to `UIManager.CRAWKWebView`.

**Comment by insraq** [comment]
Sounds good. Do you want to make the change? @shirakaba

**Comment by shirakaba** [comment]
@insraq Unfortunately I don't have time to test (and won't for a while), but here's a tentative PR: #223

@indapublic sorry for the trouble, but would you like to test whether my branch fixes your issue?

**Comment by indapublic** [comment]
@shirakaba, sure but tomorrow probably

**Comment by indapublic** [comment]
@shirakaba Looks good for me, but you are forgot change `goBack` and `goForward` methods. Just checked, I don't have any permissions for pushing to your branch. Should I create separate PR or just wait for your response?

**Comment by insraq** [comment]
@indapublic You can make a separate PR and I will merge it. Also it would be nice to extract all the duplicated code into a method.

**Comment by shirakaba** [comment]
@indapublic Sorry, find-and-replace didn't show up `goBack` and `goForward` in my interface so I missed them. I've amended the PR.

I misunderstood 'squash and merge' and looks like I've accidentally merged the amended branch it into master. I'll revert that.

> Also it would be nice to extract all the duplicated code into a method.

Makes sense! Don't have a minute to spare for that at the moment, so will leave the PR open.

**Comment by shirakaba** [comment]
Sorry, @indapublic could you make a PR of your own, referencing my original PR if you wish, that extracts the duplicated code into a method? I unfortunately don't have time at the moment to deal with it.

**Comment by indapublic** [comment]
Done @shirakaba @insraq

**Comment by insraq** [comment]
Thanks.

**Comment by indapublic** [comment]
@insraq Could yoy please notify me when npm package will be updated?
