### ISSUE TITLE
Open target="_blank" and embedded video in webview

### ISSUE THREAD

**Issue by indapublic** [CRAlpha/react-native-wkwebview#226]
When you click on the link with the target = _blank, it will open a browser window. The same behavior will be when you try to view embedded youtube.
Is it possible to open those links within webview?

**Comment by insraq** [comment]
See README:

```
openNewWindowInWebView
If set to true, links with target="_blank" or window.open will be opened in the current webview, not in Safari. Default is false.
```

**Comment by indapublic** [comment]
Sorry :( My fault
