### ISSUE TITLE
injectedJavaScript doesn't work

### ISSUE THREAD

**Issue by tomprogers** [CRAlpha/react-native-wkwebview#26]
I'm reopening this issue. Testing a non-alert scenario doesn't appear to work, and neither of the debugging techniques I've tried produce positive results.

On the native side, I inject a piece of JS code like this:

```
let js = "window.globalVariable = 'tom rules';";

return (
	<WKWebView
		source={{ uri: `file://${FS.MainBundlePath}/dist/index.html` }}
		injectedJavaScript={js}
	/>
);
```

Then, inside dist/index.html, I have this js:

```
console.log('window.globalVariable=' + window.globalVariable);
```

After launching the simulator, I attach Safari's debugger, and I inspect the document. The code I wanted to inject doesn't appear anywhere in the source. Thinking that maybe the injection is accomplished in a moar magical way, I click the reload button I've put in the web page (it does `window.location='./index.html'), and watch to see the console.log statement. I see this output:

```
window.globalVariable=undefined
```

At this point, I have yet to see a test case in which the `injectedJavaScript` prop has any effect. Any tips? How have you folks validated that it works?

**Comment by tomprogers** [comment]
I still have no idea how the injection is happening, but I found a way to verify that it is. Closing.

**Comment by insraq** [comment]
The injection happens when the page is loaded (`didFinishNavigation`)

https://github.com/CRAlpha/react-native-wkwebview/blob/master/ios/RCTWKWebView/RCTWKWebView.m#L282
