### ISSUE TITLE
WKWebView and Safari cookie

### ISSUE THREAD

**Issue by agat** [CRAlpha/react-native-wkwebview#32]
WebView does not see any cookies from Safari. This is bug?

Additional Information

React Native version: 0.36.1
Platform: iOS

**Comment by insraq** [comment]
As far as I understand, cookies are not shared between apps. So your WKWebView will not be able get cookies from Safari http://stackoverflow.com/questions/2520331/understanding-nshttpcookiestorage-for-the-iphone

However, SFSafariViewcontroller shares cookies with Safari: https://developer.apple.com/reference/safariservices/sfsafariviewcontroller
