### ISSUE TITLE
Working with Plaid Link (Supporting Custom Schemas)

### ISSUE THREAD

**Issue by indivisable** [CRAlpha/react-native-wkwebview#38]
When you try to use this link it fails with error below:

`https://cdn.plaid.com/link/v2/stable/link.html?isWebview=true&isMobile=true&key=XXX&env=tartan&product=connect&selectAccount=true&clientName=Test`

![image](https://cloud.githubusercontent.com/assets/22860891/22616970/df82705e-ea7e-11e6-82b6-1b7173396dbd.png)

Same thing happens on slideshare links as well: 
`http://www.slideshare.net/branchmetrics/the-2016-mobile-growth-handbook-64218146`

**Reference:** https://github.com/facebook/react-native/issues/9037

> WebView shouldn't trigger onLoadingError if the URL scheme itself is not supported, just like Safari.

Any ideas on how to resolve this? Also here is the code they provide using in WKWebView: https://github.com/plaid/link/blob/master/examples/wkwebview/wkwebview/LinkViewController.swift

**Comment by insraq** [comment]
You can try use `onShouldStartLoadWithRequest` props. And for plaid links, instead of load it in WKWebView, use `Linking.open()`

**Comment by abeaclark** [comment]
`Linking.open()` sends you out of the app, which isn't the best.

@insraq would you mind elaborating on `onShouldStartLoadWithRequest`? How do you see it being used here?

@indivisable you haven't come across any solutions yet, have you?

**Comment by indivisable** [comment]
@insraq Using Linking kind of defeats the purpose, it is supposed to be 'integrated' into app etc. I tried with onShouldStartWithRequest but it has to do with the custom URL schema they use which causes issue with normal WebView and WKWebView. 

@abeaclark No I ended up integrating via Objective-C and Bridge to RN
