### ISSUE TITLE
Using require('...') as source

### ISSUE THREAD

**Issue by headlessme** [CRAlpha/react-native-wkwebview#54]
I'm seeing the following error when using a require'd HTML resource as the source:

```
Possible Unhandled Promise Rejection (id: 0):
In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant.
```

Looks like it's due to this assign: 

```
    var source = Object.assign({}, this.props.source || {} , { 
      sendCookies: this.props.sendCookies,
      customUserAgent: this.props.customUserAgent
    });
```

At this point `this.props.source` is an integer from the packager, and the babel version of assign doesn't like that.

**Comment by insraq** [comment]
We never tested using `srouce={require('...')}`. I believe `source={{html: '<html>'}}` should work.
