### ISSUE TITLE
Question: How to implement immutable props like allowsInlineMediaPlayback

### ISSUE THREAD

**Issue by SRandazzo** [CRAlpha/react-native-wkwebview#57]
Hi

I was wondering what the approach should be for modifying immutable properties of WKWebView, specifically it's `configuration`.

I want to enable the `allowsInlineMediaPlayback`, however it's part of the WKWebView's `WKWebViewConfiguration`, which is a `readonly` copy property, so we cannot modify it after WKWebView has been initialized.

For my specific purposes I'm going to fork and hard code it, but how would I go about exposing this properly to ReactNative?

Thanks

**Comment by insraq** [comment]
duplicate of #55
