### ISSUE TITLE
Is there any reason to use property name `customUserAgent` instead of `userAgent` 

### ISSUE THREAD

**Issue by chuangbo** [CRAlpha/react-native-wkwebview#61]
react-native's official WebView uses `userAgent` as the property name for customization the user agent header (Android only though). see http://facebook.github.io/react-native/releases/0.43/docs/webview.html#useragent

So just wondering is there any special reason to use a different property name?

Wouldn't it better to keep the property names consistent?

Thank you.

**Comment by sportnak** [comment]
This is pure speculation:

Most likely because this is built as a ReactNative module to support WKWebView, which uses `customUserAgent`: https://developer.apple.com/reference/webkit/wkwebview/1414950-customuseragent

Also, react-native is still 0.x which inclines me and probably others to follow existing standards rather than a beta standard.

**Comment by chuangbo** [comment]
@sportnak According to the README,

> WKWebView aims to be a drop-in replacement for UIWebView.

So I reckon `WKWebView` prefer to compatible with `react-native` rather than `Apple`?

**Comment by sportnak** [comment]
a. UIWebView is an apple specific component. https://developer.apple.com/reference/uikit/uiwebview so it would follow that `Apple` standards would be preferred. 
b. This is purely speculation on my part and also not an 'issue' with this module. The naming is not confusing and does not produce and issues in implementation. I'd recommend moving this conversation to twitter: [https://twitter.com/sportnak](my handle).

**Comment by insraq** [comment]
To be honest, this originated from a PR. When it was merged, I guess no one was aware of RN has a `userAgent` prop, so WKWebView's native `customUserAgent` was used. We might need to support both in later versions.

**Comment by chuangbo** [comment]
That would be great! Thanks for the reply.
