### ISSUE TITLE
Library support/maintaning

### ISSUE THREAD

**Issue by andreyslyusar** [CRAlpha/react-native-wkwebview#66]
Thanks a lot for your work and commitment in implementing this library. 

Are you planning active supporting and maintaining it, as I can see there a couple of pull request pending merge and release.

**Comment by markdaws** [comment]
+1

I want to be able to get the HTTP Status code when the page loads, I can send a pull request, but not sure if it is something that would be merged.

Thanks.

**Comment by insraq** [comment]
This component derives from our own app, which maintains an internal copy of WKWebView. Changes are synced with this repository periodically, which goes through code review and release procedure. Unfortunately this also means we might be a bit slow responding to some of the questions.

If you guys are interested in helping maintain this repository, we could potentially add more contributors to this repo.
