### ISSUE TITLE
RCTView.h: File or directory not found / RCTViewManager.h: File or directory not found

### ISSUE THREAD

**Issue by hironarita** [CRAlpha/react-native-wkwebview#73]
I linked the library with rnpm link and I always get one of two errors when trying to build. It fails on "#import <React/RCTView.h>" in RCTWKWebView.h or "#import <React/RCTViewManager.h>" in RCTWKWebViewManager.h.

**Comment by insraq** [comment]
Hmm...We have to check whether `rnpm` still works or not. Meanwhile, you can try manually linking the library.

**Comment by hironarita** [comment]
I tried manually linking as well. I get the same issue as https://github.com/CRAlpha/react-native-wkwebview/issues/62

No errors but just a blank screen with a red line down the left side. I followed the Alternative #1 steps in the documentation. Maybe I'm missing a step? I created a Libraries folder then added the RCTWKWebView folder to it.

**Comment by hironarita** [comment]
@insraq Followed the new Alternative 1 steps but still get the same error. You also have to include React in the libraries as well correct?

**Comment by hironarita** [comment]
@insraq I finally got it to work! I had to make sure to build React in the scheme manager before WkWebView.

**Comment by jfizz** [comment]
@hironarita would you care to share a few more details (or possibly a screenshot)? I have the same issue but I can't figure out how to "build React in the scheme manager before WkWebView".
