### ISSUE TITLE
Enabling a NavBar?

### ISSUE THREAD

**Issue by matekd** [CRAlpha/react-native-wkwebview#77]
Is it possible to enable a navbar like the one shown below?

![image](https://user-images.githubusercontent.com/11228599/28965607-31bb1ff2-7912-11e7-91a9-24431095663c.png)

**Comment by insraq** [comment]
This is a different component I believe. What's shown in your screenshot is actually 
`SFSafariViewController` https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller
