### ISSUE TITLE
Take over npm module?

### ISSUE THREAD

**Issue by idris** [CRAlpha/react-native-wkwebview#8]
Since @jordansexton is not maintaining his version anymore, maybe this repo should be in charge of the npm package?

**Comment by jordansexton** [comment]
Pull requests are welcome! The project isn't abandonware, and I'd also like to see more community involvement before christening any fork. Feel free to open an issue on the source if you want to discuss.

**Comment by insraq** [comment]
I think it's generally a good idea to get this repo on NPM, maybe with a different name?

Ideally we should resolve the forks and to have one community-maintained version - to avoid the confusions to new developers. We are open for discussion under this approach. However, I have to admit, our team is quite neutral about this - we always change the code in our app first and extract them to this package. In general we do not contribute to this package directly.

**Comment by idris** [comment]
I'm fine with the name :) Jordan already owns it on npm.

I had assumed Jordan's fork was abandoned based on [his comment](https://github.com/facebook/react-native/issues/321#issuecomment-215242337): "WKWebView itself was unable to meet my needs, and I don't use it any more."

Soo... I propose we use this fork as the community-maintained version since it seems the furthest-along and most active.

Not sure who should be the main maintainer, or who should own the npm package.  I guess I'll defer to @jordansexton on that one as he's the original author.
