### ISSUE TITLE
PR this package into React Native core?

### ISSUE THREAD

**Issue by fungilation** [CRAlpha/react-native-wkwebview#82]
See https://github.com/facebook/react-native/issues/321#issuecomment-323262908

Also solves RN core's currently lousy implementation of 2 way data communication too, between RN and webview: https://github.com/facebook/react-native/pull/10941#issuecomment-323264133

**Comment by insraq** [comment]
Per this [comment](https://github.com/facebook/react-native/issues/321#issuecomment-373464088), this component should not be merged into core. Rather, we should look at other alternatives (e.g. improve RN docs)
