### ISSUE TITLE
Use rnpm

### ISSUE THREAD

**Issue by idris** [CRAlpha/react-native-wkwebview#9]
Rather than having to link things ourselves (as mentioned in the readme), this package should use rnpm.

If you agree, I'd be happy to submit a pull request for this.

**Comment by insraq** [comment]
That's a good idea. Can you submit a PR for this?

**Comment by idris** [comment]
Pull request #10 submitted a week ago.  Take a look when you have time

**Comment by insraq** [comment]
@idris Our team is currently busy working on some other issues. So we might not be able to conduct a thorough test. I can add you as a contributor to this repo since you've contributed quite a bit. Does it work for you?
