### ISSUE TITLE
crash in release build due to ViewPropType

### ISSUE THREAD

**Issue by baabgai** [CRAlpha/react-native-wkwebview#99]
In React16 View.propTypes was also depricated in favor of ViewPropTypes ([link](https://github.com/facebook/react-native/commit/53905a537a58d028fc5eb1c4e9a8ec967d8cd396)). 

In the current release (1.9.0) the Webview works fine in debug mode (without any warnings) but crashes in release mode because of View.propTypes being undefined.

The currently merged pull request for react16 seemed to miss that necessary change, but it is a very small fix can could copied from [PR88 - react capacity](https://github.com/CRAlpha/react-native-wkwebview/pull/88/commits/f41d73966b402436a9321b86e8f83821c9b203b1). After applying this patch everything seems to work with RN49.

**Comment by insraq** [comment]
Merged and released 1.10.0
